### ISSUE TITLE
Wrong data in Belgian cube

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-cube#14]
See https://github.com/trias-project/occ-cube-alien/issues/44.
A new zenodo release will be done soon.

**Comment by damianooldoni** [comment]
The software is ok. Just rerunning the pipeline for BE as I have done this morning is enough.

**Comment by damianooldoni** [comment]
As the cubes are big files, solving this issue will not result in a commit.

**Comment by qgroom** [comment]
What was the problem in the end?

**Comment by damianooldoni** [comment]
I was running these pipelines in the night. The laptop shut down automatically while the extra column with EEA cellcode was generated via random assignment. I wanted to avoid to start back from scratch so I tried to fix things locally. Bad idea. I should also have a check of the results, my fault. But it seemed there was an urgent need of a BE cube for IAS portal at INBO. That's why I was in a hurry.

**Comment by damianooldoni** [comment]
The [new version](https://zenodo.org/records/10528506) is online on zenodo.
Notice that I replaced the 20231120 tag with 20240124 in this repository. 

Collaborators may still have the old tag in their local repositories. To clean up them, open a git terminal and run:

`git pull --prune --tags`

Notice you can open a git terminal in RStudio if you prefer:

<img width="512" alt="image" src="https://github.com/trias-project/occ-cube/assets/33662631/701757da-7eaf-4e73-97b1-0bdb052c6510">
