### ISSUE TITLE
Discard occurrences with identificationVerificationStatus = unverified

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-cube#5]
Similar to https://github.com/trias-project/occ-cube-alien/issues/24.
This will improve quality and remove unverified observations, e.g.  https://www.gbif.org/occurrence/2631775528 (Natuurpunt:Waarnemingen:190863847)

**Comment by qgroom** [comment]
Did you take a look at what is populated in this field?
Would be good to know for Belgium and the world.

**Comment by damianooldoni** [comment]
No. Not yet. I have just written the issue to not forget to do it when making a new version of the cubes.

**Comment by damianooldoni** [comment]
Based on discussion on  trias-project/occ-cube-alien#24, I discard occurrences based on following values of `identificationVerificationStatus`:

- `unverified`,
- `unvalidated`,
- `not able to validate`,
- `control could not be conclusive due to insufficient knowledge`

While making occurrence cube for Slovenia at species level, I found some other suspect values which I think we should include in the list of values to discard:
- `Unconfirmed`
- `Unconfirmed - not reviewed`
- `Unconfirmed - plausible`
- `Validation requested`

@qgroom: what do you think about it?
